services:
  tts-backend:
    build:
      context: ./backend
    container_name: 73bot-backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - coeiroink

  discord-bot:
    build:
      context: ./bot
    container_name: 73bot-discord
    depends_on:
      - tts-backend
    env_file:
      - .env
    restart: unless-stopped

  coeiroink:
    build:
      context: ./coeiroink-v2
    container_name: coeiroink-v2
    volumes:
      - ./coeiroink-v2/speaker_info:/opt/voicevox_engine/speaker_info
    tty: true
    ports:
      - "50031:50031"
      - "50032:50031" # Documentation access
      - "50021:50021" # Map both ports to be safe
    command: [ "python", "./run.py", "--voicelib_dir", "/opt/voicevox_core/", "--runtime_dir", "/opt/onnxruntime/lib", "--host", "0.0.0.0", "--cpu_num_threads", "${COEIROINK_CPU_NUM_THREADS:-4}", "--load_all_models" ]
    restart: unless-stopped
